data_path: data/DIV2K_train_valid_HR/

model_d: 56
model_s: 12
model_m: 4

lr_init: 0.001
epochs: 500
batch_size: 30
steps_per_epoch: 20
val_batch_size: 20
validation_steps: 4

weights_fn: "weights/model_{epoch:05d}.h5"
